
name: Test & Upload CF IP

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时自动运行
  workflow_dispatch:        # 支持手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build CloudflareSpeedTest
        run: |
          go build -o cfst main.go
          ./cfst

      - name: Upload ip.txt to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python3 upload_to_api.py
